In [1]:
##### Lets initialize some tensors in Python/Numpy
import numpy as np


In [2]:
# tensor with randomly generated entries, order 3, dims: 2-by-3-by-4
A = np.random.rand(2,3,4)
A

array([[[0.13626785, 0.4523512 , 0.5551791 , 0.42141095],
        [0.00097821, 0.45176399, 0.01776554, 0.97553242],
        [0.96564582, 0.73541322, 0.5732585 , 0.3889422 ]],

       [[0.77204384, 0.60397388, 0.39505623, 0.87623663],
        [0.78157161, 0.9007885 , 0.73533381, 0.5252551 ],
        [0.16308785, 0.53078451, 0.50063061, 0.05065517]]])

In [3]:
# identity matrix, order 2, dims: 5-by-5 
B = np.eye(5,5)
B


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# tensor of 1's, order 4, dims: 2-by-4-by-2-by-4
C = np.ones((2,4,2,4))
C


array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [5]:
# matrix of 0's, order 2, dims: 3-by-5
D = np.zeros((3,5))
D


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# initialize complex random tensor
E = np.random.rand(2,3,4) + 1j*np.random.rand(2,3,4)
E

array([[[0.09127173+0.84791152j, 0.79727007+0.40354304j,
         0.26501719+0.92590331j, 0.44186613+0.29667833j],
        [0.17183371+0.84889693j, 0.92990726+0.03266912j,
         0.61694537+0.68031597j, 0.16550852+0.74036625j],
        [0.28602817+0.59020648j, 0.53522716+0.61678183j,
         0.49869075+0.12703561j, 0.59706036+0.42500105j]],

       [[0.16794404+0.95167045j, 0.66168467+0.84104495j,
         0.26511025+0.84873783j, 0.22781792+0.38952509j],
        [0.62413626+0.51588543j, 0.55398123+0.3770797j ,
         0.25479438+0.39505679j, 0.24688964+0.46684095j],
        [0.62632167+0.87807208j, 0.22916008+0.28894736j,
         0.10951868+0.05383367j, 0.45745724+0.79573505j]]])

In [9]:
A = np.random.rand(3,4)
B = np.random.rand(4,5)

C = A@B
C.shape

(3, 5)

In [25]:
A = np.random.rand(3,2,4)
B = np.random.rand(1,5,4)
C = np.random.rand(3,5,6)

Ap = A.reshape(3*2,4)
Bp = B.reshape(1*5,4)
Bpp = Bp.transpose()

AB = Ap@Bpp
AB.shape

(6, 5)

In [27]:

ABp = AB.reshape(3,2,1,5)
ABpp = ABp.reshape(3*2*1,5)

Cp = C.transpose(1,0,2)
Cpp = Cp.reshape(5, 3*6)

ABC = ABpp@Cpp
ABC.shape

(6, 18)

In [29]:
ABCp = ABC.reshape(2*1,3,6,3)
ABCp.shape

(2, 3, 6, 3)

In [30]:
ABCpp = ABCp.trace(axis1=1,axis2=3)
ABCpp.shape

(2, 6)

In [31]:
ABCppp = ABCpp.reshape(2,1,6)
ABCppp.shape

(2, 1, 6)

In [17]:
##### Ex.1.2(a):Transpose
A = np.random.rand(4,4,4,4)
Atilda = A.transpose(3,0,1,2)
# print(A)
# print(Atilda)

In [18]:
##### Ex.1.2(b):Reshape
B = np.random.rand(4,4,4)
Btilda = B.reshape(4,4**2)

Binary tensor contractions

In [19]:
##### Ex.1.3(a): Binary Tensor Contraction
d = 10
A = np.random.rand(d,d,d,d)  
B = np.random.rand(d,d,d,d)

Ap  = A.transpose(0,2,1,3);  Bp = B.transpose(0,3,1,2)
App = Ap.reshape(d**2,d**2); Bpp = Bp.reshape(d**2,d**2)
Cpp = App @ Bpp;             C   = Cpp.reshape(d,d,d,d)

Contraction costs

In [33]:
##### Ex.1.4(c): Tensor network evaluation
d = 10
A = np.random.rand(d,d) 
B = np.random.rand(d,d)
C = np.random.rand(d,d)
# Evaluare network via summation over internal indices
F0 = np.zeros((d,d))
for di in range(d):
    for dj in range(d):
        for dk in range(d):
            for dl in range(d):
                F0[di,dj] = F0[di,dj] + A[di,dk]*B[dk,dl]*C[dl,dj]
            
# Evaluare network via sequence of binary contractions
F1 = (A @ B) @ C
F1.shape

(10, 10)

In [34]:
F0.shape

(10, 10)

# Contraction of tensor networks


Given a tensor network composed of N tensors, there are two distinct steps needed to contract the network efficiently:

1) determine the optimal sequence of the (N-1) binary tensor contractions,

2) evaluate each of the binary contractions in turn as a matrix multiplication by taking the proper tensor permutes and reshapes.

In [37]:
from ncon import ncon
d = 10
A = np.random.rand(d,d,d); B = np.random.rand(d,d,d,d)
C = np.random.rand(d,d,d); D = np.random.rand(d,d)

TensorArray = [A,B,C,D]
IndexArray = [[1,-2,2],[-1,1,3,4],[5,3,2],[4,5]]

E = ncon(TensorArray,IndexArray,order = [5,3,4,1,2])

let's try prev example

In [51]:
A = np.random.rand(3,2,4)
B = np.random.rand(1,5,4)
C = np.random.rand(3,5,6)


In [52]:
E = ncon([A,B,C],[[2,-1,1],[-2,3,1],[2,3,-3]])
E

array([[[6.86324473, 6.68264524, 6.40262555, 7.43631696, 6.63871936,
         7.56377671]],

       [[7.80588369, 7.20383883, 5.99861225, 6.74915898, 6.32286596,
         7.32989899]]])

In [53]:
Ap = A.reshape(3*2,4)
Bp = B.reshape(1*5,4)
Bpp = Bp.transpose()

AB = Ap@Bpp
AB.shape

ABp = AB.reshape(3,2,1,5)
ABpp = ABp.reshape(3*2*1,5)

Cp = C.transpose(1,0,2)
Cpp = Cp.reshape(5, 3*6)

ABC = ABpp@Cpp
ABC.shape
ABCp = ABC.reshape(2*1,3,6,3)
ABCp.shape
ABCpp = ABCp.trace(axis1=1,axis2=3)
ABCppp = ABCpp.reshape(2,1,6)
print(ABCppp.shape)
ABCppp

array([[[3.06747476, 8.13594872, 7.75326896, 7.05614426, 7.78537415,
         4.29173385]],

       [[4.19326406, 9.57076656, 9.16220902, 8.34593128, 9.18108045,
         6.00479711]]])

In [43]:
##### Ex.1.5(c): Partial trace
d = 10
A = np.random.rand(d,d,d,d,d,d)

B = ncon([A],[[-1,-2,1,-3,-4,1]])
B.shape

(10, 10, 10, 10)

In [44]:
##### Ex.1.5(d): Disjoint networks
d = 10
A = np.random.rand(d,d)
B = np.random.rand(d,d)

C = ncon([A,B],[[-1,-2],[-3,-4]])
C.shape

(10, 10, 10, 10)